/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio_autocompletado;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author lesepulveda
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    Controlador c;

    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Text Editor");
        setIconImage(new ImageIcon(getClass().getResource("/imgs/icono.png")).getImage());
        
        c = new Controlador();
        try {
            c.Agregar_palabras();
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        Palabras_R.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddWords_Frame = new javax.swing.JFrame();
        AddWord_TxtField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Palabras_R = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ingreso_TxtField = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        AddWords_Frame.setMinimumSize(new java.awt.Dimension(290, 222));
        AddWords_Frame.getContentPane().setLayout(null);

        AddWord_TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWord_TxtFieldActionPerformed(evt);
            }
        });
        AddWords_Frame.getContentPane().add(AddWord_TxtField);
        AddWord_TxtField.setBounds(23, 61, 224, 30);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jButton2.setText("Agregar palabra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddWords_Frame.getContentPane().add(jButton2);
        jButton2.setBounds(20, 100, 140, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar palabras");
        AddWords_Frame.getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 130, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/woven-cloth-352481_960_720.jpg"))); // NOI18N
        AddWords_Frame.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 280, 190);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(785, 560));
        getContentPane().setLayout(null);

        Palabras_R.setColumns(20);
        Palabras_R.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Palabras_R.setRows(5);
        jScrollPane1.setViewportView(Palabras_R);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 350, 250, 140);

        jButton1.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1add.png"))); // NOI18N
        jButton1.setText("Agregar ");
        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, -10, 180, 90);

        jButton3.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/select.png"))); // NOI18N
        jButton3.setText("Seleccionar");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 10, 260, 57);

        Ingreso_TxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Ingreso_TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ingreso_TxtFieldKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Ingreso_TxtField);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 110, 420, 380);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1554.png"))); // NOI18N
        jLabel2.setText("Text Editor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 310, 90);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_rsz_icon-suggestion.png"))); // NOI18N
        jLabel3.setText("SUGERENCIAS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 240, 220, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/woven-cloth-352481_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -170, 830, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddWords_Frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Ingreso_TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingreso_TxtFieldKeyReleased
        Palabras_R.setText("");

        if ((Ingreso_TxtField.getText() != null) && (!Ingreso_TxtField.getText().equals(""))) {

            int k = 0;
            ArrayList<String> palabras;
            int j = Ingreso_TxtField.getText().length();

            while (j >= 0 & k == 0) {
                if (j > 0 && Ingreso_TxtField.getText().substring(j - 1, j).equals(" ")) {
                    k = j;
                }
                j--;
            }

            if (Ingreso_TxtField.getText().length() - k > 0) {
                palabras = c.buscar_palabras(Ingreso_TxtField.getText().substring(k, Ingreso_TxtField.getText().length()));

                for (int i = 0; i < palabras.size(); i++) {

                    Palabras_R.append(palabras.get(i) + '\n');

                }
            }

        }
    }//GEN-LAST:event_Ingreso_TxtFieldKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            c.Agregar_Nuevas_Palabras(AddWord_TxtField.getText());
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AddWord_TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWord_TxtFieldActionPerformed
        if ((Ingreso_TxtField.getText() != null) && (!Ingreso_TxtField.getText().equals(""))) {

        }
    }//GEN-LAST:event_AddWord_TxtFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
c.seleccionar(this, Ingreso_TxtField);
Ingreso_TxtField.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddWord_TxtField;
    private javax.swing.JFrame AddWords_Frame;
    private javax.swing.JTextPane Ingreso_TxtField;
    private javax.swing.JTextArea Palabras_R;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
