/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio_autocompletado;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author lesepulveda
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    Controlador c;

    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Text Editor");
        setIconImage(new ImageIcon(getClass().getResource("/imgs/icono.png")).getImage());
        Palabras_R.setBackground(new Color(1, 1, 1, (float) 0.01));
        Palabras_R.setLineWrap(true);

        c = new Controlador();
        try {
            c.Agregar_palabras();
        } catch (IOException ex) {
            System.out.println("error");
        }
        Palabras_R.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddWords_Frame = new javax.swing.JFrame();
        AddWord_TxtField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Palabras_R = new javax.swing.JTextArea();
        Add_Button = new javax.swing.JButton();
        Select_Button = new javax.swing.JButton();
        Save_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ingreso_TxtPane = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        Logo_label = new javax.swing.JLabel();
        Suggest_label = new javax.swing.JLabel();
        Fondo_label = new javax.swing.JLabel();

        AddWords_Frame.setMinimumSize(new java.awt.Dimension(290, 222));
        AddWords_Frame.getContentPane().setLayout(null);

        AddWord_TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWord_TxtFieldActionPerformed(evt);
            }
        });
        AddWords_Frame.getContentPane().add(AddWord_TxtField);
        AddWord_TxtField.setBounds(23, 61, 224, 30);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jButton2.setText("Agregar palabra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddWords_Frame.getContentPane().add(jButton2);
        jButton2.setBounds(20, 100, 140, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar palabras");
        AddWords_Frame.getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 130, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/woven-cloth-352481_960_720.jpg"))); // NOI18N
        AddWords_Frame.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 280, 190);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 530));
        getContentPane().setLayout(null);

        Palabras_R.setColumns(20);
        Palabras_R.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        Palabras_R.setRows(5);
        Palabras_R.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Palabras_R.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(Palabras_R);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 120, 240, 370);

        Add_Button.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        Add_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_rsz_1add.png"))); // NOI18N
        Add_Button.setText("Agregar ");
        Add_Button.setToolTipText("");
        Add_Button.setContentAreaFilled(false);
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Add_Button);
        Add_Button.setBounds(360, -20, 180, 90);

        Select_Button.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        Select_Button.setForeground(new java.awt.Color(255, 255, 255));
        Select_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_select.png"))); // NOI18N
        Select_Button.setText("Seleccionar");
        Select_Button.setContentAreaFilled(false);
        Select_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Select_Button);
        Select_Button.setBounds(180, 0, 260, 57);

        Save_Button.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        Save_Button.setForeground(new java.awt.Color(255, 255, 255));
        Save_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/if_Save_Icon_1398916.png"))); // NOI18N
        Save_Button.setText("Guardar");
        Save_Button.setContentAreaFilled(false);
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Save_Button);
        Save_Button.setBounds(520, 0, 150, 50);

        Ingreso_TxtPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Ingreso_TxtPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ingreso_TxtPaneKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Ingreso_TxtPane);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 420, 370);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(440, 120, 310, 380);

        Logo_label.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        Logo_label.setForeground(new java.awt.Color(255, 255, 255));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1554.png"))); // NOI18N
        Logo_label.setText("Text Editor");
        getContentPane().add(Logo_label);
        Logo_label.setBounds(20, 0, 310, 90);

        Suggest_label.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        Suggest_label.setForeground(new java.awt.Color(255, 255, 255));
        Suggest_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1rsz_rsz_icon-suggestion.png"))); // NOI18N
        Suggest_label.setText("SUGERENCIAS");
        getContentPane().add(Suggest_label);
        Suggest_label.setBounds(500, 20, 230, 130);

        Fondo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/woven-cloth-352481_960_720.jpg"))); // NOI18N
        getContentPane().add(Fondo_label);
        Fondo_label.setBounds(-50, -170, 830, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        AddWords_Frame.setVisible(true);
    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void Ingreso_TxtPaneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingreso_TxtPaneKeyReleased
        Palabras_R.setText("");

        if ((Ingreso_TxtPane.getText() != null) && (!Ingreso_TxtPane.getText().equals(""))) {
           

            int k = 0;
            ArrayList<String> palabras;
            int j = Ingreso_TxtPane.getText().length();


            while (j >= 0 & k == 0) {
                if (j > 0 && Ingreso_TxtPane.getText().substring(j - 1, j).equals(" ")) {
                    k = j;
                }
                j--;
            }

            if (Ingreso_TxtPane.getText().length() - k > 0) {
                palabras = c.buscar_palabras(Ingreso_TxtPane.getText().substring(k, Ingreso_TxtPane.getText().length()));


                for (int i = 0; i < palabras.size(); i++) {
                    Palabras_R.append(palabras.get(i) + '\n');

                }
            }

        }
    }//GEN-LAST:event_Ingreso_TxtPaneKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            c.Agregar_Nuevas_Palabras(AddWord_TxtField.getText());
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AddWord_TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWord_TxtFieldActionPerformed

    }//GEN-LAST:event_AddWord_TxtFieldActionPerformed

    private void Select_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_ButtonActionPerformed
        c.seleccionar(this, Ingreso_TxtPane);
    }//GEN-LAST:event_Select_ButtonActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        c.guardarArchivo(Ingreso_TxtPane, this);
    }//GEN-LAST:event_Save_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddWord_TxtField;
    private javax.swing.JFrame AddWords_Frame;
    private javax.swing.JButton Add_Button;
    private javax.swing.JLabel Fondo_label;
    private javax.swing.JTextPane Ingreso_TxtPane;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JTextArea Palabras_R;
    private javax.swing.JButton Save_Button;
    private javax.swing.JButton Select_Button;
    private javax.swing.JLabel Suggest_label;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
